
GET http://localhost:7000/api/produto/?id=1 HTTP/1.1


######

POST http://localhost:7000/api/produto HTTP/1.1
Content-Type: application/json

{
    "nome": "blalblabla",
    "descricao": "blablabla",
    "preco": 23.00
}